"use client";

import { motion } from "motion/react";

/**
 * The "Journey" handwriting wordmark as an image. The asset is black ink on a
 * transparent background (generated by `scripts/make_logo_png.py`), so it drops
 * cleanly onto any surface. Tint it to the surface:
 *   - tone "dark"  → black ink, for LIGHT backgrounds (as-is).
 *   - tone "light" → white ink, for DARK backgrounds (CSS invert).
 * Use this anywhere the word "Journey" appears (hero wordmark, back buttons).
 */
export default function JourneyLogo({
  tone = "dark",
  className = "",
}: {
  tone?: "dark" | "light";
  className?: string;
}) {
  const ink = tone === "light" ? "[filter:invert(1)]" : "";
  return (
    <motion.img
      src="/icons/journeyLogo.png"
      alt="Journey"
      draggable={false}
      className={`pointer-events-none select-none ${ink} ${className}`}
    />
  );
}
